name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Case 1
      id: test-case-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Case 1
        setup-command: npm install
        command: npm run test -- case1.test.tsx
        timeout: 10
        max-score: 3
    - name: Test Case 2
      id: test-case-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Case 2
        setup-command: npm install
        command: npm run test -- case2.test.tsx
        timeout: 10
        max-score: 1
    - name: Test Case 3
      id: test-case-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Case 3
        setup-command: npm install
        command: npm run test -- case3.test.tsx
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CASE-1_RESULTS: "${{steps.test-case-1.outputs.result}}"
        TEST-CASE-2_RESULTS: "${{steps.test-case-2.outputs.result}}"
        TEST-CASE-3_RESULTS: "${{steps.test-case-3.outputs.result}}"
      with:
        runners: test-case-1,test-case-2,test-case-3
